# Generated by Django 3.0.5 on 2024-05-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Легковой более 2т.', 'Легковой более 2т.'), ('Грузовой до 3.5т', 'Грузовой до 3.5т'), ('Грузовой выше 3.5т', 'Грузовой выше 3.5т'), ('Легковой до 2т', 'Легковой до 2т')], max_length=50),
        ),
    ]
