# Generated by Django 3.0.5 on 2024-05-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20240522_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pic/MechanicProfilePic/'),
        ),
    ]
